name: chronos
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # or cpu if no GPU
  - numpy=1.21.*
  - pip
  - pip:
    - transformers>=4.48,<5
    - accelerate>=0.32,<2
    - gluonts[pro]==0.15.*
    - datasets==2.18.*
    - typer
    - typer-config
    - joblib
    - scikit-learn
    - tensorboard
    - pytest==8.0.*
    - mypy==1.9.*
