name: time-moe
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # or cpu if no GPU
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - pip
  - pip:
    - transformers==4.40.1
    - datasets==2.18.0
    - accelerate==0.28.0
