name: uni2ts
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # or cpu if no GPU
  - numpy=1.26.*
  - scipy=1.11.3
  - pip
  - pip:
    - lightning>=2.0
    - gluonts==0.14.3
    - einops==0.7.*
    - jaxtyping==0.2.24
    - python-dotenv==1.0.0
    - hydra-core==1.3
    - orjson
    - tensorboard
    - multiprocess
    - huggingface_hub>=0.23.0
    - safetensors
    - datasets==2.17.1
    - jax[cpu]
