name: normwear-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip
  - pip:
    - tqdm
    - tabulate
    - timm>=0.6.0
    - transformers>=4.20.0
    - pytorch_pretrained_vit
    - chronos[torch]
    - datasets
    - accelerate
    - einops
