name: units
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # or cpu if no GPU
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - tqdm=4.64.1
  - pyyaml
  - pip
  - pip:
    - einops==0.4.0
    - patool==1.12
    - reformer-pytorch==1.4.4
    - sktime==0.16.1
    - sympy==1.11.1
